Repository healtheloper/todo-list, pull requests merged in 2022-04, with the labels that each got.

#4 Env: Create Issue Template (#3)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#5 [Park] Teamplte 설정 및 Readme 작성 (Env #3)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#6 [BB] Webpack + Babel, Lint 설정 등 환경설정(env #1)
  front/.eslintrc.js
  front/.gitignore
  front/.prettierrc
  front/babel.config.json
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/webpack.config.js
Labels: fe-feat

#7 [Park] JSON server 생성 및 CRUD 구현 (Feat #2)
  back/.gitignore
  back/db.json
  back/package-lock.json
  back/package.json
  back/server.js
  back/utils.js
Labels: be-feat

#23 [BB] 1주차 PR 리뷰 반영하여 환경 설정 수정
  front/.eslintrc.js
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/webpack.config.js
Labels: fe-리뷰반영

#24 [Park&BB] 함수형 컴포넌트를 위한 기반 코드 제작
  front/.eslintrc.js
  front/src/core/peact.js
  front/webpack.config.js
Labels: fe-feat

#25 [Park] PR 리뷰 반영 + 서버 변경 (JSON server -> express)
  back/.eslintrc.js
  back/.gitignore
  back/.prettierrc
  back/babel.config.json
  back/db.json
  back/init.js
  back/package-lock.json
  back/package.json
  back/server.js
  back/src/app.js
  back/src/common/constants.js
  back/src/common/utils.js
  back/src/controllers/columnController.js
  back/src/controllers/logController.js
  back/src/controllers/todoController.js
  back/src/db.js
  back/src/models/Column.js
  back/src/models/Todo.js
  back/src/models/TodoLog.js
  back/src/routers/columnRouter.js
  back/src/routers/logRouter.js
  back/src/routers/todoRouter.js
  back/utils.js
Labels: be-리뷰반영

#27 [BB] lint import order 환경설정
  front/.eslintrc.js
Labels: fe-feat

#28 [BB] lint import order 환경설정
  back/.eslintrc.js
Labels: be-feat

#30 [BB] HTML+CSS 구조 잡기
  front/src/_reset.scss
  front/src/index.css
  front/src/index.css.map
  front/src/index.html
  front/src/index.scss
Labels: fe-feat

#31 [Park&BB] 카드 컴포넌트 작성
  front/src/App.module.css
  front/src/components/Column/Card/Card.js
  front/src/components/Column/Card/card.module.css
  front/src/components/Column/CardWritable/CardWritable.js
  front/src/components/Column/CardWritable/cardWritable.module.css
  front/src/components/Column/Cards/Cards.js
  front/src/components/Column/Cards/cards.module.css
  front/src/components/Column/Header/header.module.css
  front/src/sceleton.html
Labels: fe-feat

#32 [Park & BB] Component 구조 설계 및 axios 환경 설치
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/src/App.js
  front/src/App.module.css
  front/src/common/domUtils.js
  front/src/components/Actions/Action/Action.js
  front/src/components/Actions/Action/action.module.css
  front/src/components/Actions/Actions.js
  front/src/components/Actions/actions.module.css
  front/src/components/Column/Card/Card.js
  front/src/components/Column/Card/card.module.css
  front/src/components/Column/CardWritable/CardWritable.js
  front/src/components/Column/CardWritable/cardWritable.module.css
  front/src/components/Column/Cards/Cards.js
  front/src/components/Column/Cards/cards.module.css
  front/src/components/Column/Column.js
  front/src/components/Column/Header/Header.js
  front/src/components/Column/Header/header.module.css
  front/src/components/Column/column.module.css
  front/src/components/Header/Header.js
  front/src/components/Header/header.module.css
  front/src/components/Main.js
  front/src/components/main.module.css
  front/src/core/peact.js
  front/src/hooks/useId.js
  front/src/index.css
  front/src/index.css.map
  front/src/index.html
  front/src/index.js
  front/src/reset.css
  front/src/sceleton.css
  front/src/sceleton.html
  front/src/service/columnApi.js
  front/src/service/todoApi.js
  front/src/tagComponents/Button.js
Labels: fe-feat

#35 [Park] HTML, CSS sceleton 구조 삭제
  front/src/sceleton.css
  front/src/sceleton.html
Labels: fe-feat

#38 [Park] Swagger 연동 및 명세 작성
  back/package-lock.json
  back/package.json
  back/src/app.js
  back/src/controllers/columnController.js
  back/src/router.js
  back/src/routers/columnRouter.js
  back/src/routers/todoRouter.js
  back/src/swagger/options.js
  back/src/swagger/schemas/column.yaml
  back/src/swagger/schemas/createColumn.yaml
  back/src/swagger/schemas/createTodo.yaml
  back/src/swagger/schemas/todo.yaml
  back/src/swagger/swagger.js
Labels: be-feat

#44 [BB] 브라우저 처음 로딩시 칼럼 갯수 표시
  front/src/components/Column/Card/Card.js
  front/src/components/Column/Card/card.module.css
  front/src/components/Column/Cards/Cards.js
  front/src/components/Column/Column.js
  front/src/components/Column/Columns.js
  front/src/components/Column/Header/Header.js
  front/src/components/Column/columns.module.css
  front/src/components/Main.js
  front/src/service/columnApi.js
  front/src/service/todoApi.js
Labels: fe-feat

#47 [Park] eslint 환경설정 및 back scripts 수정
  back/package.json
  front/.eslintrc.js
Labels: env

#48 [BB] 브라우저 로딩시 정렬된 칼럼 표시
  front/src/components/Content/Cards/Cards.js
  front/src/components/Header/Header.js
Labels: fe-feat

#56 [Park & BB] Deploy front using gh pages
  front/package-lock.json
  front/package.json
  front/src/service/columnApi.js
  front/src/service/logApi.js
  front/src/service/todoApi.js
  front/webpack.config.js
Labels: fe-feat

#57 [Park] production 환경에서 cors 에 access 할 url 도메인 설정
  back/src/common/constants.js
  back/src/middlewares/cors.js
  package.json
Labels: be-feat

#58 [BB] column 타이틀 옆 +, x 버튼 이벤트
  front/src/components/Content/CardWritable/CardWritable.js
  front/src/components/Content/CardWritable/cardWritable.module.css
  front/src/components/Content/Cards/Cards.js
  front/src/components/Content/Column/Columns.js
  front/src/components/Content/Column/columns.module.css
  front/src/components/Content/ColumnHeader/ColumnHeader.js
  front/src/components/Content/ColumnHeader/columnHeader.module.css
Labels: fe-feat

#60 [Park] 2주차 1번째 PR 반영 리팩터링
  front/.eslintrc.js
  front/src/App.js
  front/src/common/constants.js
  front/src/common/domUtils.js
  front/src/components/Content/Columns/Columns.js
  front/src/components/Content/Columns/columns.module.css
  front/src/components/Content/Content.js
  front/src/components/SideContent/Action/Action.js
  front/src/components/SideContent/SideContent.js
  front/src/core/peact.js
  front/src/tagComponents/Button.js
Labels: fe-feat

#61 [Park] date utils & actions 시간 차이 표시
  front/src/common/dateUtils.js
  front/src/common/utils.js
  front/src/components/SideContent/Action/Action.js
Labels: fe-feat

#62 [Park] webpack devtool 설정 반대로 되어있던 것 수정
  front/src/components/Content/Card/Card.js
  front/src/components/Content/CardWritable/CardWritable.js
  front/webpack.config.js
Labels: fe-bug

#63 [Park] 카드 더블클릭 시 수정 가능, 수정 요청 보내기
  back/src/middlewares/cors.js
  front/src/common/dateUtils.js
  front/src/components/Content/Card/Card.js
  front/src/components/Content/Card/card.module.css
  front/src/components/Content/CardWritable/CardWritable.js
  front/src/components/Content/CardWritable/cardWritable.module.css
  front/src/components/Content/Cards/Cards.js
  front/src/components/Content/Cards/cards.module.css
  front/src/core/peact.js
  front/src/service/todoApi.js
Labels: fe-feat

#65 [BB] 새로운 카드 등록
  front/src/components/Content/CardWritable/CardWritable.js
  front/src/components/Content/CardWritable/cardWritable.module.css
  front/src/components/Content/Cards/Cards.js
  front/src/components/Content/ColumnHeader/ColumnHeader.js
  front/src/components/Content/ColumnHeader/columnHeader.module.css
  front/src/components/Content/Columns/Columns.js
  front/src/service/todoApi.js
Labels: fe-feat

#64 [BB] 리뷰 PR관련 리팩토링 - Modal, Card
  front/src/App.js
  front/src/components/Content/Card/Card.js
  front/src/components/Content/Card/card.module.css
  front/src/components/Content/CardWritable/CardWritable.js
  front/src/components/Content/Cards/Cards.js
  front/src/components/Content/ColumnHeader/ColumnHeader.js
  front/src/components/Content/Columns/Columns.js
  front/src/components/Modal/Modal.js
  front/src/components/Modal/modal.module.css
  front/src/components/SideContent/Action/Action.js
  front/src/components/SideContent/SideContent.js
Labels: fe-리뷰반영

#66 [Park] visible 처리 로직, input 값 체크 로직 추가, Webpack alias 설정
  front/.eslintrc.js
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/Content/Card/Card.js
  front/src/components/Content/CardWritable/CardWritable.js
  front/src/components/Content/CardWritable/cardWritable.module.css
  front/src/components/Content/Cards/Cards.js
  front/src/components/Content/ColumnHeader/ColumnHeader.js
  front/src/components/Content/Columns/Columns.js
  front/src/components/Content/Content.js
  front/src/components/Header/Header.js
  front/src/components/Modal/Modal.js
  front/src/components/SideContent/Action/Action.js
  front/src/components/SideContent/SideContent.js
  front/src/index.js
  front/src/tagComponents/Button.js
  front/webpack.config.js
Labels: fe-bug, env
